### ISSUE TITLE
Histórias de Usuário nº 1 - Sistema de combate

### ISSUE THREAD

**Issue by gabriezim** [jao45gg/POKEMON#1]
## Deve haver um sistema de combate
 
Como jogador, em um combate existente deve haver a determinação de uma carta ganhadora e perdedora mediante a diferença de defesa e ataque, **a carta que ataca deve ter mais _dano_ que a _defesa_ da carta que defende**, para que a partida prossiga.

### Critérios de aceitação

- > Cartas possuem quantias de **_Dano_** e **_Defesa_** que variam mediante à carta individual.
- > Deve haver um sistema que determina quando uma carta ataca e a outra defende.
- > Cartas perdedoras devem ser descartadas.
- > Cartas descartadas não podem ser reutilizadas em um mesmo combate, a não ser que ocorra uma __exceção__.
<sub> __Exceções__ poderão ser adicionadas em outras histórias, podem ser curas, "__revives__", habilidades, __etc__ </sub>

### Pré Requisito

- Deve existir conjuntos de baralhos.

**Comment by jao45gg** [comment]
Fechado
