### ISSUE TITLE
Histórias de Usuário nº 10 - Seleção de deck

### ISSUE THREAD

**Issue by Christianssgithub** [jao45gg/POKEMON#10]
> ## Deve haver um sistema de criação de deck
>Para a escolha das cartas para compor o seu deck, deve ser possível escolher entre três tipos de cartas, sendo elas: **Pokémons;**

> ### Critérios de aceitação
> * > No deck de ver conter no máximo **X** cartas.
> * > No deck não pode conter mais do que 4 da mesma carta.

> ### Pré-Requisito
> * >O usuário possuir a carta que quer usar em seu deck.

**Comment by gabriezim** [comment]
Comentário, há a possibilidade da remoção da energia, cada carta fará uma habilidade
