### ISSUE TITLE
Histórias de Usuário nº12 - Sistema de cartas

### ISSUE THREAD

**Issue by gabriezim** [jao45gg/POKEMON#12]
## Sistema de cartas

Eu como usuário, desejo ter cartas em meu jogo, que contenham características e informações acerca do dano e defesa dos pokemons contidos e usados em jogo, para que eu possa jogar.

### Critérios de aceitação

- Deve haver um tipo base para a construção de cartas.
- Essas cartas devem descrever as informações e características de um pokemon.
- Deve ser possível criar e salvar essas cartas em arquivos de texto.

**Comment by jao45gg** [comment]
Fechado
