### ISSUE TITLE
Histórias de Usuário nº 3 - Cartas com tipo

### ISSUE THREAD

**Issue by gabriezim** [jao45gg/POKEMON#3]
## Cartas devem ter tipo

O usuário pode ter acesso à determinados tipos elementais de cartas relacionados ao tipo do pokemon (*em uma mecânica semelhante a um jogo de pedra, papel, tesoura*). Dessa forma, cartas de tipos que são **super efetivos** a um outro, possuem o dobro da defesa e o dobro do ataque contra aquele tipo de  carta.

### Critérios de avaliação

- > Cartas devem ter uma variável de tipo associada ao pokemon em questão
- > Tipos devem possuir uma fraqueza em que ele é **inefetivo**, nesse caso, o tipo receberá o dobro do dano e fará metade do dano
- > Tipos devem possuir uma força em que ele é **super efetivo**, nesse caso, ele dará o dano e terá o dobro da defesa

### Pré Requisito

- Deve exitir um tipo base para a criação de cartas.

**Comment by jao45gg** [comment]
Fechado
