### ISSUE TITLE
Histórias de Usuário nº 6 - Efeitos

### ISSUE THREAD

**Issue by thaismadeira10** [jao45gg/POKEMON#6]
# **Efeitos**
Como uma jogadora eu gostaria que existissem efeitos funcionais e aplicáveis associados a habilidades das cartas pokémons, possibilitando a adoção de estratégias e táticas, sendo eles: paralisado - em que o pokémon afetado não joga por uma rodada -, confuso - em que o pokémon afetado deve rodar a moeda para decidir se ataca ou toma dano -, dormindo - em que o pokémon afetado deve rodar a moeda para decidir se joga ou continua dormindo -, envenenado - em que o pokémon toma dano a cada rodada -, e furioso - em que o pokémon afetado tem seu dano dobrado -.
### Critérios de aceitação
- As consequências dos efeitos devem ser aplicadas ao respectivo pokémon imediatamente após a utilização da habilidade associada a ele;
- Deve haver uma maneira de controlar a frequência de utilização dos efeitos para evitar vantagem injusta;
### Pré-requisitos
- Sistema de cartas;
- Sistema de combate;
- Ação de combate;

**Comment by thaismadeira10** [comment]
completar mais tarde

**Comment by thaismadeira10** [comment]
• Disponibilidade de utilizar esses efeitos durante a rodada.
• Disponibilidade de usar os efeitos que dependem da sorte pra saber como eles vão ser utilizados.

**Comment by thaismadeira10** [comment]
• Disponibilidade de utilizar esses efeitos durante a rodada.
• Disponibilidade de usar os efeitos que dependem da sorte pra saber como eles vão ser utilizados.

**Comment by thaismadeira10** [comment]
**Pré Requisito**
• Existência de efeitos.
• Disponibilidade de usar os efeitos.

**Comment by gabriezim** [comment]
**Efeitos.hpp**, **Efeitos.cpp**, **Habilidades.hpp** e **Habilidades.cpp** foram feitos.
