### ISSUE TITLE
Histórias de Usuário nº 7 - Quem vai iniciar o jogo

### ISSUE THREAD

**Issue by thaismadeira10** [jao45gg/POKEMON#7]
# **Quem vai iniciar o jogo**
Como uma jogadora eu gostaria de uma forma justa e aleatória de selecionar qual jogador irá iniciar a partida através do sorteio de uma moeda entre os dois jogadores.
### Critérios de aceitação
- Os jogadores deverão escolher uma das faces da moeda antes de iniciar a partida para definir seu iniciador.
- É preciso garantir que a moeda gere um resultado aleatória a cada novo início de partida.
### Pré-requisitos
- Seleção de equipes.
- Sistema de combate.

**Comment by thaismadeira10** [comment]
**Critérios de aceitação**

•A escolha de quem irá começar no jogo deve ser feita de forma aleatória, seja no dado, na moeda, ou de outra forma.
•É preciso definir quem vai iniciar cada rodada e como isso vai ser feito, para que assim o início da rodada não seja feito sempre pela mesma pessoa.

**Comment by thaismadeira10** [comment]
**Pré Requisito**
• Dois ou mais jogadores.
• Existência de alguma maneira aleatória de ser escolhido quem vai iniciar a jogada.

**Comment by jao45gg** [comment]
Fechado
