### ISSUE TITLE
Histórias de Usuário nº 8 - Cartas prêmio

### ISSUE THREAD

**Issue by uchoaluiz** [jao45gg/POKEMON#8]
### **Pré-requisitos**
- Baralhos;
- Sistema de distribuição de cartas no início de partidas;

# **Cartas prêmio**
Como um jogador eu gostaria de poder marcar o placar de partidas e estabelecer uma condição de vitória para partidas do jogo, de modo que sejam distribuídas e reservadas 6 cartas prêmio a cada jogador no início de cada partida, retiradas do baralho de cada um imediatamente após o embaralhamento, de modo que cada jogador seja recompensado com uma de suas 6 cartas prêmio a cada eliminação de pokémon adversário e ganhe aquele que receber todas elas primeiro.

### **Critérios de aceitação**
- O jogo deve ser finalizado imediatamente quando algum dos jogadores receber todas as suas 6 cartas prêmio;
- Deve haver um placar em arquivo de texto que contabiliza o número de cartas prêmio adquiridas por cada jogador ao longo da partida;

**Comment by jao45gg** [comment]
Fechado
